/**:
  ros__parameters:
    wheel_radius: 0.305
    wheel_width: 0.205
    wheel_base: 2.7 # between front wheel center and rear wheel center
    wheel_tread: 1.54 # between left wheel center and right wheel center
    front_overhang: 0.96 # between front wheel center and vehicle front
    rear_overhang: 0.785 # between rear wheel center and vehicle rear
    left_overhang: 0.115 # between left wheel center and vehicle left
    right_overhang: 0.115 # between right wheel center and vehicle right
    vehicle_height: 2.0
    max_steer_angle: 0.70 # [rad]
